-- CRIAR NOVO BD
CREATE DATABASE GREENHOUSE;

-- UTILIZANDO O BD
USE GREENHOUSE;

-- CRIANDO UMA TABELA
CREATE TABLE `GREENHOUSE`.`PLANTS`(
	`PLANT_NAME` CHAR(30) NOT NULL,
    `SENSOR_VALUE` FLOAT NULL,
    `SENSOR_EVENT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `SENSOR_LEVEL` CHAR(5) DEFAULT NULL,
    PRIMARY KEY `PK_PLANT_NAME` (`PLANT_NAME`)
);

-- COMANDOS DML DE INSERÇÃO DE DADOS
INSERT INTO `GREENHOUSE`.`PLANTS` (`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`) VALUES('Orquidea', '10', 'HIGH');
INSERT INTO `GREENHOUSE`.`PLANTS` (`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`) VALUES('Samambaia', '11', 'LOW');
INSERT INTO `GREENHOUSE`.`PLANTS` (`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`) VALUES('Babosa', '9', 'LOW');
INSERT INTO `GREENHOUSE`.`PLANTS` (`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`) VALUES('Palmeira', '15', 'HIGH');
INSERT INTO `GREENHOUSE`.`PLANTS` (`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`) VALUES('Coqueiro', '20', 'HIGH');
INSERT INTO `GREENHOUSE`.`PLANTS` (`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`) VALUES('Pinheiro', '25', 'HIGH');
INSERT INTO `GREENHOUSE`.`PLANTS` (`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`) VALUES('Canhamo', '420', 'HIGH');
INSERT INTO `GREENHOUSE`.`PLANTS` (`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`) VALUES('Girassol', '2', 'LOW');
INSERT INTO `GREENHOUSE`.`PLANTS` (`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`) VALUES('Violeta', '666', 'MED');
INSERT INTO `GREENHOUSE`.`PLANTS` (`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`) VALUES('Mandioca', '51', 'LOW');

-- EXECUTANDO COMANDOS DQL
-- consultando tudo da tabela
SELECT * FROM `GREENHOUSE`.`PLANTS`;

SELECT `PLANT_NAME`, `SENSOR_EVENT` FROM `GREENHOUSE`.`PLANTS`;

-- aplicar filtros nos registros de dados
SELECT * FROM `PLANTS` WHERE `SENSOR_LEVEL` = 'HIGH' AND `SENSOR_VALUE` >= 10 AND `SENSOR_VALUE` <= 20;

SELECT * FROM `PLANTS` WHERE `SENSOR_LEVEL` IN ('HIGH', 'LOW');

-- CLAUSULA DE ORDENAÇÃO
SELECT * FROM `PLANTS` WHERE `SENSOR_VALUE` < 420 ORDER BY `SENSOR_VALUE` DESC;

-- FUNÇÕES DE AGRUPAMENTO
SELECT COUNT(*), `SENSOR_LEVEL` FROM `PLANTS` GROUP BY `SENSOR_LEVEL`;

-- SQL SELECT TOP
SELECT * FROM `PLANTS` WHERE `SENSOR_VALUE` LIMIT 3;

-- SQL MIN AND MAX (MENOR E MAIOR VALOR)
SELECT MIN(`SENSOR_VALUE`) FROM `PLANTS`;
SELECT MIN(`SENSOR_VALUE`) FROM `PLANTS` WHERE `SENSOR_LEVEL` = 'HIGH';
SELECT MAX(`SENSOR_VALUE`) FROM `PLANTS`;
SELECT MAX(`SENSOR_VALUE`) FROM `PLANTS` WHERE `SENSOR_LEVEL` = 'HIGH';

-- SQL COUNT (AGRUPAMENTO)
SELECT COUNT(*) FROM `PLANTS`;
SELECT COUNT(*) FROM `PLANTS` WHERE `SENSOR_LEVEL` = 'HIGH';

-- SQL SUM (SOMA)
SELECT SUM(`SENSOR_VALUE`) FROM `PLANTS`;
SELECT SUM(`SENSOR_VALUE`) FROM `PLANTS` WHERE `SENSOR_LEVEL` = 'HIGH';

-- SQL AVG (AVERAGE)
SELECT AVG(`SENSOR_VALUE`) FROM `PLANTS`;
SELECT AVG(`SENSOR_VALUE`) FROM `PLANTS` WHERE `SENSOR_LEVEL` = 'HIGH';

-- SQL LIKE (SELECIONAR ALGO ESPECIFICAMENTE ( _ PARA AS LETRAS QUE NÃO APARECEM DA PALAVRA))
SELECT * FROM `PLANTS` WHERE `PLANT_NAME` LIKE '_a_o_a'; -- ORDEM ESPECÍFICA
SELECT * FROM `PLANTS` WHERE `PLANT_NAME` LIKE '%a%o%a'; -- TODOS QUE TEM AS LETRAS
SELECT `PLANT_NAME` FROM `PLANTS` WHERE `PLANT_NAME` LIKE '_a_o_a'; -- APARECE SÓ O NOME DA PLANTA (COM O * APARECE TUDO)
SELECT * FROM `PLANTS` WHERE `PLANT_NAME` LIKE 'a%'; -- AS QUE COMEÇAM COM A LETRA A
SELECT * FROM `PLANTS` WHERE `PLANT_NAME` LIKE '%a%'; -- AS QUE TEM A LETRA A NA PALAVRA
SELECT * FROM `PLANTS` WHERE `PLANT_NAME` LIKE '%a'; -- AS QUE TEM A LETRA A NO FINAL DA PALAVRA

-- COMANDO UPDATE PARA ATUALZIAR REGISTROS DE DADOS
SELECT * FROM `PLANTS`;
UPDATE `PLANTS` SET `SENSOR_VALUE` = 90, `SENSOR_LEVEL` = 'HIGH' WHERE `PLANT_NAME` = 'Babosa';

-- APAGANDO REGISTROS DA TABELA DO BANCO DE DADOS
DELETE FROM `PLANTS` WHERE `PLANT_NAME` = 'Coqueiro';