-- PESSOA
INSERT INTO PESSOA(
	ID_PESSOA,
    NOME,
    MATRICULA,
    DATA_NASC,
    CONTATO
) VALUES (7, 'Jake', 777, 20021115, 71717171);

-- ORGANIZADOR GERAL E SIMPÓSIO

INSERT INTO ORGANIZADOR(
	ID_ORGANIZADOR,
    MATRICULA,
    CARGO
) VALUES (1, 'San', 999, 19990710);

INSERT INTO SIMPOSIO(
	ID_SIMPOSIO,
    NOME,
    DATA_INICIO,
    DATA_FIM,
    LOCAL_REALIZACAO
) VALUES (1, 'MCountdown', 20241001, 20241010, 'Korea');

-- TIPO DO EVENTO, MINISTRANTE E EVENTO

INSERT INTO TIPO_EVENTO(
	ID_TIPO_EVENTO,
    DESCRICAO
) VALUES (1, 'Show');

INSERT INTO MINISTRANTE(
	ID_MINISTRANTE,
    MATRICULA,
    CARGO
) VALUES (3, 'Soobin', 333, 'Líder');

INSERT INTO EVENTO(
	ID_EVENTO,
    ASSUNTO,
    CARGA_HORARIA,
    DATA_INICIO,
    DATA_FIM
) VALUES (1, 'Kpop', 4, 20241004, 20241004);

INSERT INTO EVENTO(
	ID_EVENTO,
    ASSUNTO,
    CARGA_HORARIA,
    DATA_INICIO,
    DATA_FIM
) VALUES (2, 'Drama', 6, 20241007, 20241007);

-- PARTICIPANTE E INSCRIÇÃO NO SIMPÓSIO

INSERT INTO PARTICIPANTE(
	ID_PARTICIPANTE,
    MATRICULA
) VALUES (10, 101010);

INSERT INTO INSCRICAO(
	ID_INSCRICAO,
    VALOR,
    DATA_INSCRICAO
) VALUES (15, 120.00, 20240716);

-- TEMA, AUTOR DO ARTIGO, ARTIGO DO TEMA, JURADO DA COMISSÃO, COMISSÃO CIENTÍFICA, PARECER DO JURADO SOBRE O ARTIGO

INSERT INTO TEMA(
	ID_TEMA,
    NOME,
    DESCRICAO
) VALUES (1, 'Enhypen', 'Gostosas');

INSERT INTO AUTOR(
	ID_AUTOR,
    MATRICULA,
    CARGO
) VALUES (4, 'Heeseung', 'Vocal');

CREATE TABLE ARTIGO(
	ID_ARTIGO INT NOT NULL AUTO_INCREMENT,
    TITULO TEXT NOT NULL,
    RESUMO TEXT NOT NULL,
    TEXTO TEXT NOT NULL,
    ID_TEMA INT NOT NULL,
    ID_AUTOR INT NOT NULL,
    PRIMARY KEY(ID_ARTIGO),
    CONSTRAINT FK_ID_TEMA_ARTIGO FOREIGN KEY(ID_TEMA) REFERENCES TEMA(ID_TEMA),
    CONSTRAINT FK_ID_AUTOR FOREIGN KEY(ID_AUTOR) REFERENCES AUTOR(ID_AUTOR)
);

CREATE TABLE JURADO(
	ID_JURADO INT NOT NULL AUTO_INCREMENT,
    CARGO VARCHAR(20) NOT NULL,
    MATRICULA INT NOT NULL,
    ID_PESSOA INT NOT NULL,
    PRIMARY KEY(ID_JURADO),
    CONSTRAINT FK_ID_PESSOA_JURADO FOREIGN KEY(ID_PESSOA) REFERENCES PESSOA(ID_PESSOA)    
);

CREATE TABLE COMISSAO_CIENTIFICA(
	ID_COMISSAO INT NOT NULL AUTO_INCREMENT,
    ID_TEMA INT NOT NULL,
    ID_ARTIGO INT NOT NULL,
    ID_JURADO INT NOT NULL,
    PRIMARY KEY(ID_COMISSAO),
    CONSTRAINT FK_ID_TEMA_COMISSAO FOREIGN KEY(ID_TEMA) REFERENCES TEMA(ID_TEMA),
    CONSTRAINT FK_ID_ARTIGO_COMISSAO FOREIGN KEY(ID_ARTIGO) REFERENCES ARTIGO(ID_ARTIGO),
    CONSTRAINT FK_ID_JURADO_COMISSAO FOREIGN KEY(ID_JURADO) REFERENCES JURADO(ID_JURADO)
);

CREATE TABLE PARECER(
	ID_PARECER INT AUTO_INCREMENT NOT NULL,
    NOTA FLOAT NOT NULL,
    DESCRICAO VARCHAR(256) NOT NULL,
    ID_ARTIGO INT NOT NULL,
    ID_JURADO INT NOT NULL,
    PRIMARY KEY(ID_PARECER),
    CONSTRAINT FK_ID_JURADO_PARECER FOREIGN KEY(ID_JURADO) REFERENCES JURADO(ID_JURADO),
    CONSTRAINT FK_ID_ARTIGO_PARECER FOREIGN KEY(ID_ARTIGO) REFERENCES ARTIGO(ID_ARTIGO)
);