CREATE DATABASE DADOS_FUNCIONARIO;

USE DADOS_FUNCIONARIO;

CREATE TABLE DADOS_CADASTRAIS(
	MATRICULA INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    DATA_NASC DATETIME NOT NULL,
    NACIONALIDADE VARCHAR(50) NOT NULL,
    SEXO VARCHAR(10) NOT NULL,
    EST_CIVIL VARCHAR(10) NOT NULL,
    RG INT NOT NULL,
    CPF INT NOT NULL,
    ENDERECO VARCHAR(256) NOT NULL,
    DATA_ADMISSAO DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE CARGOS_OCUPADOS(
	CARGO VARCHAR(50) NOT NULL,
    DT_INICIO DATETIME NOT NULL,
    DT_FIM DATETIME NOT NULL
);

CREATE TABLE DEPARTAMENTO_LOTAÇÃO(
	DEPTO VARCHAR(50) NOT NULL,
    DT_INICIO DATETIME NOT NULL,
    DT_FIM DATETIME NOT NULL
);

CREATE TABLE DEPENDENTES(
	NOME VARCHAR(100) NOT NULL,
    DATA_NASC DATETIME NOT NULL
);